/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  owner: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  buy_and_store_data: {
    buy_token_ids: string[];
    cart_price_usd: Uint128;
    encrypted_data: string;
  };
} | {
  withdraw_funds: {
    amount: Uint128;
  };
};
export type Uint128 = string;
export type QueryMsg = {
  get_encrypted_data: EncryptedData;
};
export type Binary = string;
export interface EncryptedData {
  address: Binary;
  [k: string]: unknown;
}