/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import * as _0 from './Buy.types'
import * as _1 from './Buy.client'
import * as _2 from './Buy.message-composer'
export namespace contracts {
  export const Buy = { ..._0, ..._1, ..._2 }
}
